### ISSUE TITLE
prepare MEME file from Homer output 

### ISSUE THREAD

**Issue by poorvam** [flatironinstitute/inferelator-prior#10]
HI,

Can Homer output from "findMotifsGenome.pl" (http://homer.ucsd.edu/homer/ngs/peakMotifs.html) be used to run infereletor prior?

Thanks,
Poorva

**Comment by asistradition** [comment]
If you run the inferelator-prior pipeline using `--scan HOMER` it will use HOMER to search for motifs. There is no convenient way to use the existing results of a previously-run FIMO or HOMER search.

**Comment by poorvam** [comment]
Thank you for responding so promptly. I can sure use --scan HOMER option, but what file format is needed to run 'python -m inferelator_prior.network_from_motifs --scan HOMER'? 

link - http://homer.ucsd.edu/homer/ngs/formats.html

**Comment by asistradition** [comment]
There are three supported formats for the motif file (e.g. the file provided by `-m MyMotifs.file`), and you can select them with the `--motif_format` switch. `--motif_format meme` is the default (for MEME files), but `--motif_format homer` (for MOTIF files) and `--motif_format transfac` (for TRANSFAC flatfiles) should also work.

I would note that virtually all of the testing is with MEME files (and the homer and transfac formats aren't strict standards), so it's preferable to use MEME files, everything else being equal. That said, all three formats will work.

**Comment by poorvam** [comment]
HI, 

Thank you for your comments on using --motif_format homer but this isnt helping. See below

The format of homer motif file is here "http://homer.ucsd.edu/homer/ngs/formats.html", go to "Motif files"


COMMAND LINE - "python -m inferelator_prior.network_from_motifs -m peaks/knownResults/known1.motif --scan HOMER --motif_format homer -f GRCm38.primary_assembly.genome.fa -g gencode.vM25.primary_assembly.annotation.gtf --species mouse  -c 10 -o $output"

Loading genes from file (gencode.vM25.primary_assembly.annotation.gtf)
55487 genes loaded
Promoter regions defined with window (50000, 2000) around TSS
Loading motifs from file (peaks/knownResults/known1.motif)
	1 motifs loaded
Scanning target chromatin (None) for motifs (peaks/knownResults/known1.motif)
Traceback (most recent call last):
  File ".../opt/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File ".../opt/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../inferelator-prior/inferelator_prior/network_from_motifs.py", line 482, in <module>
    main()
  File ".../inferelator-prior/inferelator_prior/network_from_motifs.py", line 63, in main
    save_locs_filtered=args.save_locs_filtered)
  File ".../inferelator-prior/inferelator_prior/network_from_motifs.py", line 285, in build_motif_prior_from_genes
    save_locs_filtered=save_locs_filtered, num_cores=num_cores)
  File ".../inferelator-prior/inferelator_prior/network_from_motifs.py", line 460, in scan_and_build_by_tf
    prior_matrix = pd.concat(prior_matrix, axis=1)
  File ".../opt/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    sort=sort,
  File ".../opt/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
