### ISSUE TITLE
Python Script Arguments for Network_From_Motifs subpackage

### ISSUE THREAD

**Issue by odagayev** [flatironinstitute/inferelator-prior#9]
Hi, 

I'm having trouble understanding how to write a script for the network_from_motifs subpackage. Can you please advise what the variable names should be or what the format of the input should be if I want to run the package from a .py file? 

Here is what I am trying to run in an `inferelator_prep.py` file: 
```
import inferelator_prior 
from inferelator_prior import network_from_motifs as nm


FA_file = "Homo_sapiens.GRCh38.dna.primary_assembly.fa"
GTF_file = "Homo_sapiens.GRCh38.105.gtf"
MOTIF_MEME_file = "hg.cisbp.meme"
OUT_destination = "./hg_cisbp"

nm.main(motif=MOTIF_MEME_file, gtf = GTF_file,fasta =FA_file, out= OUT_destination)
```

Here is the error I am seeing: 
```
[od344@cn-0014 Inferelator_new]$ python inferelator_prep.6.py 
Traceback (most recent call last):
  File "inferelator_prep.6.py", line 10, in <module>
    nm.main(motif=MOTIF_MEME_file, gtf = GTF_file,fasta =FA_file, out= OUT_destination)
TypeError: main() got an unexpected keyword argument 'motif'
```

Thank you for your help!

**Comment by asistradition** [comment]
You can either call the `network_from_motifs` package as a script with `python -m inferelator_prior.network_from_motifs` and provide command line arguments, or you can call it from an external script:

```
import inferelator_prior 
from inferelator_prior import network_from_motifs as nm


FA_file = "Homo_sapiens.GRCh38.dna.primary_assembly.fa"
GTF_file = "Homo_sapiens.GRCh38.105.gtf"
MOTIF_MEME_file = "hg.cisbp.meme"
OUT_destination = "./hg_cisbp"

nm.build_motif_prior_from_genes(MOTIF_MEME_file, GTF_file, FA_file, output_prefix=OUT_destination)
```
The `main()` function from that package should be run only when the module is executed directly, and parses command line arguments to pass to the `build_motif_prior_from_genes` function in that file. There's a full docstring on `build_motif_prior_from_genes`, but it's not compiled into actual documentation.

In general, I think that it's probably easier to execute from the command line (`python -m inferelator_prior.network_from_motifs ---help` is pretty comprehensive), but there are certainly good reasons to call it from a fixed script and there is no functionality that is inaccessible from `build_motif_prior_from_genes()`.

EDIT - if you don't call it from the command line, make sure to set `build_motif_prior_from_genes(lowmem=True)`, which is essential for large genomes, and I have just realized is incorrectly set to `False` by default in the `build_motif_prior_from_genes` function, but is correctly set to `True` as a default by the command line parser.

**Comment by odagayev** [comment]
Understood - thank you!
